---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: kafka-stack
  labels:
    provider: helm
    service: kafka
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: kafka.poc.crossplane.io/v1beta1
    kind: CompositeKafka

  resources:
    - name: k8s-providerconfig
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: ProviderConfig
        spec:
          credentials:
            source: InjectedIdentity
      patches:
        - fromFieldPath: spec.parameters.name
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-provider-config"

    - name: helm-providerconfig
      base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: ProviderConfig
        spec:
          credentials:
            source: InjectedIdentity
      patches:
        - fromFieldPath: spec.parameters.name
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-provider-config"

    - name: strimzi-release
      base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        spec:
          forProvider:
            chart:
              name: strimzi-kafka-operator
              repository: https://strimzi.io/charts/
            namespace: kafka
            skipCreateNamespace: false
            wait: true
            values:
              service:
                type: ClusterIP
          providerConfigRef:
            name: CHANGE-ME
      patches:
        - fromFieldPath: spec.parameters.name
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-strimzi"
        - fromFieldPath: metadata.uid
          toFieldPath: metadata.uid
        - fromFieldPath: spec.parameters.name
          toFieldPath: spec.providerConfigRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-provider-config"

    - name: strimzi-kafka
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: kafka.strimzi.io/v1beta2
              kind: Kafka
              metadata:
                namespace: kafka
                name: 
              spec:
                kafka:
                  replicas: 3
                  listeners:
                    - name: plain
                      port: 9092
                      type: internal
                      tls: false
                    - name: tls
                      port: 9093
                      type: internal
                      tls: true
                      authentication:
                        type: tls
                  storage:
                    type: jbod
                    volumes:
                    - id: 0
                      type: persistent-claim
                      size: 2Gi
                      deleteClaim: false
                  config:
                    offsets.topic.replication.factor: 2
                    transaction.state.log.replication.factor: 1
                    transaction.state.log.min.isr: 1
                    default.replication.factor: 1
                    min.insync.replicas: 1
                zookeeper:
                  replicas: 3
                  storage:
                    type: persistent-claim
                    size: 2Gi
                    deleteClaim: false
                entityOperator:
                  topicOperator: {}
                  userOperator: {}
      patches:
        - fromFieldPath: spec.parameters.name
          toFieldPath: spec.providerConfigRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-provider-config"
        - fromFieldPath: spec.parameters.name
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-strimzi-kafka"