apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: kafka-composition
  annotations:
    provider: helm
spec:
  crossplane:
    version: ">=v1.4.0"

  # dependsOn:
  #   - provider: crossplane/provider-helm
  #     version: ">=v0.10.0"
  #   - provider: crossplane/provider-kubernetes
  #     version: ">=v0.3.0"